CREATE TABLE task
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                             NOT NULL,
    description TEXT,
    status      VARCHAR(255)                             NOT NULL,
    due_date    date,
    CONSTRAINT pk_task PRIMARY KEY (id)
);