CREATE TABLE users
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                             NOT NULL,
    username  VARCHAR(255)                             NOT NULL,
    password  VARCHAR(255)                             NOT NULL,
    user_role VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);